### ISSUE TITLE
请问下大佬试过多显卡用LAMB吗

### ISSUE THREAD

**Issue by keyang3** [ymcui/LAMB_Optimizer_TF#1]
tesla v3 pod  2TiB 的内存， TitanX才12GB， 只能放6个512。。我真是白激动一场
我试了下horovod的 tf 的 bert 改lamb optimizer 但
`UnknownError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
	 [[node DistributedLAMBOptimizer_Allreduce/HorovodAllgather_gradients_concat_1_0 (defined at <string>:162) ]]`

**Comment by ymcui** [comment]
抱歉，才看到，我没在多显卡环境下用LAMB。实验都是在TPU下完成的。
